name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
- title: '🚀 Features'
  labels:
  - 'feature'
  - 'enhancement'
- title: '🐛 Bug Fixes'
  labels:
  - 'fix'
  - 'bugfix'
  - 'bug'
- title: '🧰 Maintenance'
  label: 'chore'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

exclude-labels:
- release/no-impact

version-resolver:
  major:
    labels:
    - 'bump/major'
  minor:
    labels:
    - 'bump/minor'
  patch:
    labels:
    - 'bump/patch'
  default: patch

template: |
  ## Changes

  $CHANGES
