version: '3'

services:
  db:
    image: postgres:${POSTGRES_TAG:-latest}
    shm_size: 1gb
    ports: [6543:5432]
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

  web:
    build: .
    image: concourse/concourse:local
    command: web
    depends_on: [db]
    ports: [8080:8080]
    volumes:
    - .:/src
    - "./hack/keys:/concourse-keys"
    - "./docker-compose-config:/config"
    environment:
      CONCOURSE_CONFIG_FILE: /config/concourse.yml

  worker:
    build: .
    image: concourse/concourse:local
    command: worker
    privileged: true
    depends_on: [web]
    ports:
    - 7777:7777
    - 7788:7788
    volumes:
    - "./hack/keys:/concourse-keys"
    - "./docker-compose-config:/config"
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_WORKER_CONFIG_FILE: /config/concourse.yml
